### ISSUE TITLE
Recommend a similar and more complete open source project

### ISSUE THREAD

**Issue by w4454962** [eteran/reader#1]
This project also supports manual execution of lexical analyzer with code.

https://github.com/Genivia/RE-flex

**Comment by eteran** [comment]
Thanks, but I think that things like RE-flex are **much** more complicated than what my class here is looking to do. Personally, I think such tools are significantly more complicated than necessary.

I'm not sure that I need "more complete" as I've been using this as the basis of many parsers I've written in the past and have never really found it lacking.

I appreciate the info though!
